version: '3.9'

services:
  db:
    image: postgres
    container_name: test-db
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    networks:
      - test-environment

networks:
  test-environment: